#!/bin/bash
fswatch -0 ../source | xargs -0 -n 1 sh -c "python3 gensite.py && osascript -e 'tell application \"Safari\"' -e 'repeat with w in windows' -e 'repeat with t in tabs of w' -e 'if URL of t contains \"file:///\" then' -e 'set URL of t to (get URL of t)' -e 'end if' -e 'end repeat' -e 'end repeat' -e 'end tell'"

